### ISSUE TITLE
Priest spell Power Word: Solace Cooldown not showing

### ISSUE THREAD

**Issue by Molotov11** [Maczuga/WeakAuras2-MoP#12]
The talent "Solace and Insanity" replaces Holy Fire with Power Word: Solace. Tracking the cooldown with WeakAuras doesn't work, the Icon is not appearing at all. Holy Fire works fine.

String:

!WA:2!1v1tVTrru86AvALbbTonM2QkHPserLGkOccsvcKY6SMAi12S7gs5K9S7(S3HSEMrZmRDCUvFQN9hbFMt(aFaQ4dWkl(aGYhHCIJ8MzTDBrqoKDM38M3F(9(9BCPMvhvnUA8l)8f0ioZNNjJG7FLvKmDcx2rOPCMQICANbduG(O3zjHfHh0Ltz6WgUTdC9wfX5PX8jm)jub0xCZOmLMpkaotFSiMOHWm7NxTXp34HqIKezJ9(EknrQReoGYOQKko4hDL5d4mDZuYqLSZXbh1QT7LycbjJK(ZGuHx8KlpfaXbkbeP9iyOsMty0rMvS9ZF3MRIZK2n90tf4vaS7IvoMnomodEfquGVwcSH6KRpZSlaplVMZicL1mFN8BNVBET8p8653b)8E)BlxO00OtNE46SK4yQyXnBkPNx)NYiXOzs9GGfQSqpyOPtV3lRjQQruPNkHG4WZlW0sZT2m)7bFIqCZ3WJg8uU8hkvQu5lkScPdSiVZbhh0rSJ1ioP4M2o6eASoX5aC7L2dgqpdITgFXQIP2VSoJVYE(VIJj6GP5xBHKRX5JzG50UtB38DLyvB8zH1XiBzug)ROunDA(9FRE5TJ8yQIgMcjRS7MWLXNijIzNSEXQTrXI4FW6E(nyw5xt8XBrf0tj2G9e900rqpHeIOggqzXD)p8PyHNX14xNiF65WDxJcBWDXh9)LI4PmYiAusycqhMObNuoj(3VikLOuyzg3ZW6QeQjPatVxOIYgMc74nklvtRTtFhZX7L)TLZ)UklYuqVch7p3S2gK(osEkudpFMXMXF8wynU105ifnXZ6mgPWUETC9dWdLMdAfRU6SnT1dxftvIuYuFnj6uv16lIbfrB4LqY8TuM8RnBJ(R)cPLrAqFhJQFHrBqTYX7TNxuceD6(sTKoCiilpBmrsj44CbN1yDe8gtsZGYYOecBiGxk)4(Zesok00tZ)XLkBPyZ7sNobbDEMxRV)PbEVMjfIPCaDyfXT3uvg63HuLjtXjEtm8wy5ajzKrLIIPYIBve2gyJJs0riKg2QTFRdDDoNZhvYXOe6VqZJgx8eXn(J)6b0yz3tEIF9ghoBDdPE)9Y9E5T9WGgDAEO4wg4EiWajnYpHpPdR)Q3A7cf(5G0jKPQlqDbmgtCxjGYlp)UUhDKzE1GNHdye5dZgmWGRYN6Eu3MhFu(UE40nnD7n9rhONTSxJd8d65hCGxGDENHV61FU112ylFNs)9fEw)f3DdOxVRKpuckv9p1343df7yUjCg(sAVT3mzLeiP(B2kQ2LpbK1nAVNu3NNsIGvR5CfE0FMDjYPQ4yQIqdxcKEOeaNSZDqucFmBGwMXSfuEOLhBHV(llERVxcngY)65iiuaY1Yv34fFL4wMh5hdbfgFgpg(TR4rsfjKYxwigBAgWgal0VHNRBB5zfQZpR8JZOXlFitEkp4B2No6qjLzMRqsEN(lxt5BHSORUKYkKV4iVM4o0HmUew)lxUMk2vk5svF7Jxn2YaRQ8(Yh94h9fvh)Np)F(

**Comment by Maczuga** [comment]
Solution:
![image](https://user-images.githubusercontent.com/544349/109347534-97e6f580-7873-11eb-90bf-65904e48e2d4.png)

Why?
![image](https://user-images.githubusercontent.com/544349/109347638-bea52c00-7873-11eb-97fe-26a921816a21.png)

So... The issue is - as I explained earlier somewhere - it's either Tauri or MoP issue. Spells that replace others or come from talents sometimes are not recognized as known ones.

WeakAuras is unable to detect the PW:S (and other spells) ID, because:
```[20:48] Dump: value=GetSpellLink("Power Word: Solace") 
[20:48] empty result 
[20:48] Dump: value=GetSpellLink("Holy Fire") 
[20:48] [1]="|cff71d5ff|Hspell:129250|h[Power Word: Solace]|h|r"
```

Both GetSpellLink and IsSpellKnown fail for such spells.

**Comment by Maczuga** [comment]
Also have found some info about that from some IRC chat archive:
https://infobot.rikers.org/%23wowuidev/20140928.html.gz

This is how MoP behaves. Talents that replace spells are not considered as known (Solace, certain Druid talents with multiple IDs for each spec, DKs have 1 talent too).

You have to check this flag I have showed earlier.

I have tried pre-fetching all spells from spellbook as known, but Solace exists with Holy Fire ID there.
