### ISSUE TITLE
Druid talents (Incarnation, Force of Nature and Heart of the Wild (all have spec variants)) not able to show CD information

### ISSUE THREAD

**Issue by Vyrdi** [Maczuga/WeakAuras2-MoP#15]
## Describe the bug
For some reason the talents listed above are not able to be loaded through triggers for On cooldown or not on cooldown. Tracking their aura works fine but there is issues with the cooldowns. I cannot really list more information as it just doesn't work for some reason.

Hopefully I gave you enough info here and thanks for supplying a working version of WA2 for MoP!

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

**Comment by Maczuga** [comment]
Same issue as https://github.com/Maczuga/WeakAuras2-MoP/issues/12

**Comment by Maczuga** [comment]
https://github.com/Maczuga/WeakAuras2-MoP/issues/12#issuecomment-786860652
You might wanna try this.

**Comment by Maczuga** [comment]
https://github.com/Maczuga/WeakAuras2-MoP/commit/ef6e8518da562b16973bd1b8544844b83f603513
Show be fixed, releasing 1.2.3 in a minute
