### ISSUE TITLE
Weakauras stopped working after update from 1.2.5 to 1.2.6

### ISSUE THREAD

**Issue by JakubJukl** [Maczuga/WeakAuras2-MoP#17]
## Describe the bug
After updating to newest version 1.2.6, my warlock dynamic group stopped working, icons stopped showing cooldown and maybe even more. Upon opening WA2 settings window, Swatter displayed the error code attached below. On other classes it works ok, although it worked ok for some time on warlock aswell and I did no changes to my warlock Weakauras.

**Do you have an error log of what happened?**

```plaintext
Date: 2021-04-27 20:27:54
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\WeakAuras\RegionTypes\Icon.lua line 580:
   attempt to call method 'Pause' (a nil value)
..\AddOns\WeakAuras\RegionTypes\Icon.lua line 580:
   in function `Update'
..\AddOns\WeakAuras\WeakAuras.lua line 3787:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:3786>
..\AddOns\WeakAuras\WeakAuras.lua line 3876:
   in function <..\AddOns\WeakAuras\WeakAuras.lua:3843>
..\AddOns\WeakAuras\WeakAuras.lua line 3959:
   in function `UpdatedTriggerState'
..\AddOns\WeakAuras\WeakAuras.lua line 3726:
   in function `UpdateFakeStatesFor'
..\AddOns\WeakAuras\WeakAuras.lua line 3699:
   in function `FakeStatesFor'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua line 1860:
   in function `PriorityShow'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua line 1653:
   in function `PriorityShow'
...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua line 663:
   in function <...terface\AddOns\WeakAurasOptions\WeakAurasOptions.lua:632>

Debug:
   
Locals:
None
AddOns:
  Swatter, v5.20.5464 (RidiculousRockrat)
  WeakAuras, v1.2.6
  WeakAurasOptions, v1.2.6
  BlizRuntimeLib_enUS v5.4.8.50400 <hu.logon.tauri.hu>
  (ck=90)
```

### To Reproduce

I got no idea, my weakauras are attached below.

1. Import my weakauras.
2. Log to a destruction warlock.
3. Open weakauras with /wa.

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

Yes, I did.

**Which version of WeakAuras are you using?**

Version 1.2.6
**Was it working in a previous version? If yes, which was the last good one?**

Yes it works well in 1.2.5
### Additional Info

[WeakAuras.zip](https://github.com/Maczuga/WeakAuras2-MoP/files/6386842/WeakAuras.zip)

**Comment by Maczuga** [comment]
Can you export me that dynamic group? 1.2.6 is working fine with all my auras.

**Comment by Maczuga** [comment]
Should be fine with 1.2.7
