### ISSUE TITLE
Show On: Match Count -> Remaining Time does nothing

### ISSUE THREAD

**Issue by snwflake** [Maczuga/WeakAuras2-MoP#18]
## Describe the bug
Setting an aura to `Match Count` with a remaining time should in fact activate the trigger when the condition is met.

**Do you have an error log of what happened?**
Swatter didn't catch anything

### To Reproduce
Import the following (preferably on a shaman...anything with a buff that last some time will probably replicate)
```
!WA:2!Drv3QnUruyNMc7IUkBOnuc9IqkeO0Yswx6cf6c1YrETlo2bj72U0S1EKMJ8mnsZiMzKtCUQRVOSx7hbFDVspcL(aim9bOKNGsEc6zKCYf1Gz(rZ5mNVFoZoD2pDF6(03)fR5rsrGmxfbFAd1IHXXAW097IpANFRrJgferetQUqYfMW2Edg55NTxuU2ithb3ygNrjgimVAqrImCPq)sFTHOmoUCb34egJdAMZsJIpBgO0dorTD67)4MkiT5xD6PRi5kIGKc6dZ2RpFgZi4IzhfW4qcDtkXeXaDatE9qXgD1W517DNopeMdcZfkiMFJFWfE97xKRHjgPmXWZyfrY0qUaoxsHcBSDX0dAtrnkMW4uW3WtbQRzrg4BRKM3BZafbwCC7eIwZE8EcWT43umPDRGrtcg1YF066Zncdw11R)fDg33V6OHDbsIHP4I5iSHPU5iFeMLqwakfEbdq8oDPodss6r1o3HB9ALmpBsKmxyyfi3meZjXivh)TV6UhWrnWxBHsF51is8RjUY9cXm4dPtxHHxZWofuU(xZfOWmhAselYEgPA(O6VBjL)OX9O4ckbj5hW6evW3C)vaK1cRSiJpb1u2knKexzck)W70gE0vlod5jRCZCJLcZQMNEAZJCLj01it5dZSgbNqgy1Y35Mij0FFLLuJS05uxLmboWpnhLih1TsbGmWheAijiVDq5RCwApRTaM6xfXjHA0qKaHbDBDERb4jCTF9Ks3DRMZVfQcZwlb4IxSbbULQdmKOR0UUJ70rDZdM75)7oO3UXYi0JqLxlyf6QJTfHRvv1VvrDTDhRX)uEL32zdj3GnedZQxM9rpKdB7WzCnjmbOSM5CAHB(B(MxpO5po29ZlpFQ)1CQH9oFssgJSB2ZQVX2y9s4IuRDP3GGEN55ERuMUJlEnYPRnYO51AYt)R)5yo94(bRicEAfZ)YYN2zdDRmmXAErxMTu1Lh6kqo9pbIgcmkqmZWEYs7klMkFRBkENDk)5YllpS8TL)YtkNGdo))DkIvOZctaXq29(6xc6y3YMLWG2(EEd8JKjs13Vl(leV7y(mNYpJH9eAIXwAaBLvt6KqMPvdhpQFVbEfB1MEyazFzpR5lMebxAxRVmW2qmzGnCyYJVfu)uqbxelv1W)GSpHptivWwTWZ2Z5PusLE6kdQgTFSY2x7)IN385F9(Z)7F6)o
```

1. Create Icon
2. Edit trigger: `Aura`, `Player`, `Buff`, `Spell ID/Name` (Lightning Shield in my case), `Show On: Match Count`, `Remaining Time <= 300`

**Screenshots**
![](https://i.imgur.com/zQzb6hJ.png)
![](https://i.imgur.com/4cTfls8.png)

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No.

**Which version of WeakAuras are you using?**
 3901317 1.2.4

**Was it working in a previous version? If yes, which was the last good one?**
Only recently converted.

### Additional Info

n/a

**Comment by Maczuga** [comment]
But the match count options row below are not set. You have to set count and the operator (< <= = etc)

**Comment by snwflake** [comment]
Please disregard, I'm an idiot.
