### ISSUE TITLE
Death runes not updating properly

### ISSUE THREAD

**Issue by Aqinog** [Maczuga/WeakAuras2-MoP#21]
Hello again and thanks for adding death runes ! However I've noticed 2 issues with them: 

Currently the rune type (death or regular) is determined when the rune starts recharging and not when the rune is spent. This is an issue since it makes it harder to know if a fully-depleted rune will be a regular or a death one.
I made a rune bar and tracked death runes with a condition to change the bar color and backdrop appropriately, the top bar is made with weakauras, the bottom one comes with ElvUI: 
![WoWScrnShot_052721_235026](https://user-images.githubusercontent.com/69145216/119903162-939ca800-bf48-11eb-9948-856fdcd8acc5.jpg)
As you can see, the backdrop shows the wrong color (red or blue instead of purple).

The second issue is that after a certain time out of combat, the runes reset to their normal state meaning any death rune goes back to being a regular one. This isn't shown by the weakaura and the runes are still shown as death runes instead of regular ones.
![WoWScrnShot_052721_235056](https://user-images.githubusercontent.com/69145216/119903279-c9419100-bf48-11eb-8ed3-ea093ca7bac2.jpg)
Same here, top bar is WA, bottom one is ElvUI.

**Comment by Maczuga** [comment]
Export your weakaura for bars, i have no issues with mine

**Comment by Deathsperate** [comment]
!WA:2!9A5YZTnYryCXcL8AJujXsETwlBNnkVKDCwZirjrBL4nYcsKMuVixqszlhNqoayibSbbGNbGsu5nZUP8zEkN559epUhDLlPso0LQCmPQu(qoLt(VGmnaOeLsY6xLnQYMad6zW0933VEuIThNRnBYujNn14nh3yCJN8HhOr0FKbZ1BfxBx2AsssfLMj5c98D1BrzClxNt)N(NptZLzqzkXH6DwfBR93NWmMQSRRTVLhBVc1RZP(x(0ArHAYAhnsUB7nYi3EKrs0JrBiwTYT9OQnyUbE9IISK1(0rFA09rt5m9JEkAhLircjvUoXMkfpJmgnOEJv6XbegDQSb22tDxtlFkJO7l(a80QCFcZxwRULJf3uwr8JVChFMvJgIm6ItZIV9p0ZGQfuVoULy5YSrXSv2qXh3FKagjvhUh12oVbx(z8anAlQJFjr0w71V6klxQC1sLxwTSsGyX18SjTPmvhstkxwnmuTCuITV5HtTiJkMQAPIz2yJUboXBb5(ehDtxwrxlXuwjZwLZO(CXTuMdXE7O6)oXLJ8oIAJuxIJvtcMOPHXZ(ukHtl5ZOon8nFpysfhxh6bgITpgrvmzyCQURJbVdgkMQWhP0Ky5Kf(bIjaFeCDij8df)EUtoY32Y45ZNCk1ahkFQvxFkfRgk2UeJSA(c1WXFc1MbcXxwruO0NaMxwv3MW54DkCHQI30Votuue7qIpr65rjBwCiCNOvAf1mz26asGVy4cEHYNCQalJ(BKEo39xPG7Dwmvxo1UEybcUspr5un0hXL1ePvDRgY9W0ZkAU9TCQ7YIQpYDdTz5fV2lvESMwNOtFa(m)bLqTT6QuIV56ownm9RML5Up1bt27sjEUoJR)WNmtpUhH9O7Az4BE(EwIzwYnGPtV8iWPkoAQujNBo40jGPHRCqyGQU(HF6eEJDSN301GQSCLYfuW1Weo)xBAyI)vNaoTkt8bRjQ6FiCz4B4ngoudQdLzPxY0D3co1GVL3yH7ZPI2OH6bmLm8DGVB4kGoWAWLKflX3ubxoPdo2k0Jl(zz7DjT5pdJNOXDzA4wQg8bWfGVNS3yi60IwoYuIV6ZhjmDRQpORGeC1DGRHEUt6BM5f7K6OrIPzjbnlWooXh9OuZNgwNI4(DsalDTjGj7J4Nygvf)R1brM)QUHHKyWJroPuIiIPJQOJtkUps82gBDe36QAllULMnT2GWPIMiWzHj7kCurdPzsX67KqQT7I1PqZCnyo0gdPNwJB50WM2F1mlxo36BL)o5kJVyHWxFd8)FwyUOiqddSeMA5vx17SIvAzJhgW9PguJnj7zQsS9mjsWpwggtuoLHZjdVVyUnDD9nlYCBWOIp7jNOLW1CgwCHb(jWv6gkpCldQQA4E5w9ROoFt925tPOvrzFx3Mj6hUHYfMwFmZNUNOOtv3u48TIm2h2ZxkshkhfI3vpcxwHW9fjUcH9Gk5V(rpD9sHg8WPzcsIdjI)AwggcmARmBNrvDxeCko68ZNmDA4MsWIWps0u5PIUiUgH(4PMdUTmZYbpQHwByZW9s03Lzj6Yecq9Yvqn)9lSv5L3aw(ItRQBs1FuAycPoTimlIqy7AGmcUMQTi2bujMUjXPbLFTPHoRLBP)9FhV(h5w6lUiEDjjPoEIJYOm)2qLOq(Rxo8k3s)XlGxFqULGZIxFDj4tFoEmj2pXXiSObkYWND0CegTNmdK58WVmb2zi9nsU4IXDgG7KaYb5H1gG9W6hY7Wgc8g2mMMrag54TQbfgfkcFcOoGqHsF(iq5tWHiGj4SH4WtmY5(VgPsiacBBc3ng2G71ceG39HFk8aj4NfYmWpVgufHdOgqqEa0gWbletdGoyCOXhOqDOHjQWhVMaw1GhkmUWJqllA5THMcfhCtaEFm8yGb8OKYhcGwr(iyxyp0PaMsq7yZZjCnZlC7MFIZkCMYnMtln8lQbzf9K)vWVgDhWVbDgWVf(Dqhj43))1aaF6lJYdFgQ1rO67J0AKqNn8mGtn7SZLm9cV6s9wd6ydf(kFPsnw3QSwc8PxFv7i9AO2vduntu1sKBP)YLWRlE4ndREVUn(hi53QF71ybLVFLCL29MdP(cRWqkpQYIJH5(d6n0(49ocDgXggHKlyT36kEyZ5Hq7tn7clMCUzFJy7V6Bl2(n0L8LY2cnBig4eGDSMGkTqWrv6LrFNputV5ruoAfVv)1FS9mzD3XOI63)Day))26FeJlYN3e4(9EPG7eV1GBr1DiJ8RphFKElyGuZmFYfVXGE5Oahl33Q)SlK2BZDtnZvvFiAzgUL(WQC0Fiq3k5gq6VRO6q5(ppjEDHJDM9PsTWmjtp3je7Jh(RcKFM3(c)lIxfo1t2b)1OTYXy7HfT5ps1VPEHDwy9mfx1I(IojhDKctZ70tShV1F7E)Nd

**Comment by Maczuga** [comment]
Should be fixed with 0884badacb104f2e35444cddf2f10784754beb32
