### ISSUE TITLE
Glow - Pixel Glow

### ISSUE THREAD

**Issue by itsmekasta** [Maczuga/WeakAuras2-MoP#4]
Pixel glow on icon appears as missing texture instead being transparent.
Probably missing **.png**?

![](https://i.imgur.com/P0jOzBd.png)

**Comment by Maczuga** [comment]
More info on that: seems to be related to X/Y Offset, as with those values set to 0 all was fine.

![image](https://user-images.githubusercontent.com/544349/98378463-57eecf00-2046-11eb-8a1a-c4c1d4058704.png)

**Comment by itsmekasta** [comment]
Yap, I figured it's indeed working with new icons.
I was modifying a retail code.

![](https://i.imgur.com/4hY9rbp.pngl)

**Comment by Maczuga** [comment]
Reopening it as there is still issue with offset x/y giving green BG on borders.
