### ISSUE TITLE
Global conditions not working

### ISSUE THREAD

**Issue by Kumase** [Maczuga/WeakAuras2-MoP#8]
Seems like the Global Condition "In Combat" isn't working at all. (And everything else under Global Condition, except for Always True, for that matter)

![image](https://user-images.githubusercontent.com/43862731/99723680-415a6600-2a91-11eb-8092-12e3571b6c26.png)

Made a simple icon that should glow whenever the condition is met, tried both In Combat = True and Flase.
Also tried giving a bar an icon and a few others things but nothing.

**Comment by Maczuga** [comment]
Could you export the WeakAura please?

**Comment by Kumase** [comment]
!WA:2!DrvWUTTrquR6w0aEOiwnnijia1if2h6bJAvevKB1uwkwbksku0X2fgqEj5qTBn1US7Uu2YNA0PCwFc6qp1t6lOWOFaecf9CH)e8xqNDPKBs5bIzEZSZmVzNzl1O8WYrLJE)3mJfk49ezYq4PRjVStCSc0h8hXRvAn8toEjWp25x)edWCcpKkKDfmUoOw92(19wekejrIl49UGLcND9k16rdaQRj8Nnrlzdgas1xSTCP4VjZuqBYq4SPKmjHJsQNeSB1D)Hx8CpyeGH)aGKOP3OYcS6DLqm7sVEDR3Q1evkKK0ms5CN5EzXO559RTxp)(983ZZ3nJZ0bPjKXG0ZMahx94uWZKWkZIGa8i(iG8G6T624WwtZ4lRoN0niHA2iWVq)1Ii43x7wK0GKtsElsfMG)MBphG09WAju7r0mbDQcsITnN8pdtGIOXuPb6mSk9Gb4zuF77FqAznCPUVIsW(0XfD4sPp2cA)flKdjOdlfC5com9oZpBlv69)GiutKiKVQuPsRFtb6QAWDVd97K(LwqsMwGHIfEelstD3dvVTixSlHil47wuC5EYYk6AR9FotPzXJr(ifAKl(iOB7oTRN)ijYkJpZSogAlJ1XVPljbxNE)gs2vB(Mmse2hiB67)rCFvMwyXUqiJosssNC0sHIcyetXcsGZwY5pyamDJMTBx3RVBhF)oV2R5lpWFXDPUh7k4Xlz0XFuEmwTx7Do0VvZ21)7fdsex0qc)sgWdh39t)UDQ88c2zmm38BveMyumhErqMwl4DgbsCaBMbUfWhOPFL1)vmBQrP2DDMRXH(xUcH6AmsTz3NYcpNdk162t0lKKafITyi8g2e4I9fqsdOaBav)o3ebjQQRz87HEdZs0mhVWeIs9W8UoUkK)gHzs7CNPMZVN3f2l6PeoZmmi4v9uAIu34AGOGEAPLcFE(JY3ArKz0fDPVzNrQaCrosnX4NnwB5oKW4nYpY6D(X5NK)t5BfeZ4mf9)dpNXlgLX45mZejMru9KT9cPq45vZDE6AtgrKmcEvpHXdfddiAVrKKmyDziLWhGVpSDEWztsLcSE0Jn7u7uzhBJ5kHyyjPzLfdA1836KFQJlwjANzAr4OI1179N)ZZyr30KVznB030huAV)BSDESeFKaBc4K663wm50Waz4BqVAE1R3UsglAE6jFV3Uvgvv9I9dqUeZg4izCtwaA6dw9(NzrzFMYqOiQhjjLswFEetzEqQjES0VUP55KysiCQrxDkgJ(PGUpwaHKbWKvrIUa3EXIPtQLFoLvv2hgvE0FD8)(d

Made a random one that tracks the current prince buff just for the sake of testing.
